#!/usr/bin/env bash
# This script creates a PID file and handles signals

mkdir -p /var/run
echo "$$" > /var/run/myscript.pid

cleanup() {
  rm -f /var/run/myscript.pid
  exit
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 2
done

