#!/usr/bin/env bash
# This script creates a PID file and handles signals

echo "$$" > /run/myscript.pid

cleanup() {
  rm -f /run/myscript.pid
  exit
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 2
done

